# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false

#install:
#  - R -e 'devtools::install_deps(dep = T)'

warnings_are_errors: false

#cache: packages
r_packages:
  - covr
  - devtools

after_success:
  - Rscript -e 'library(covr); codecov()'
